- name: Install docker
  dnf:
    name: docker
    state: latest
- copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
- name: Install kubernetes
  dnf: name={{ item }} state=latest
  with_items:
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni
